---
- name: ensure repository dotfiles exists
  git:
    repo: "https://github.com/cecepm/dotfiles.git"
    dest: "~/.dotfiles"

- name: create symlinks
  file: src=~/.dotfiles/{{ item }} dest=~/{{ item }} state=link force=yes
  with_items:
  - .inputrc
  - .bashrc
