---
- name: ensure git and vim is installed
  apt: name={{ item }} state=installed
  with_items:
  - git
  - vim
  sudo: yes

- name: ensure repository vim-dotfiles exists
  git:
    repo: "https://github.com/cecepm/dotfiles-vim.git"
    dest: "~/.vim"

- name: ensure repository vundle exists
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "~/.vim/bundle/Vundle.vim"

- name: copy vimrc
  command: cp ~/.vim/vimrc ~/.vimrc creates=~/.vimrc

# dirty hack, avoiding an error when running PluginInstall
- name: comment colorscheme options
  lineinfile: >
    dest='~/.vimrc'
    regexp='^colorscheme molokai'
    line='"colorscheme molokai'
    state=present

- name: install all bundle
  command: vim +PluginInstall +qall

# now we can safely activate colorscheme options
- name: comment colorscheme options
  lineinfile: >
    dest='~/.vimrc'
    regexp='^"colorscheme molokai'
    line='colorscheme molokai'
    state=present
