---
- name: ensure git and vim is installed
  apt: name={{ item }} state=installed
  with_items:
  - git
  - vim
  sudo: yes

- name: ensure repository vim-dotfiles exists
  git:
    repo: "https://github.com/cecepm/dotfiles-vim.git"
    dest: "~/.vim"
    update: no

- name: ensure repository vundle exists
  git:
    repo: "https://github.com/gmarik/vundle.git"
    dest: "~/.vim/bundle/vundle"
    update: no

- name: copy vimrc
  command: cp ~/.vim/vimrc ~/.vimrc creates=~/.vimrc

# dirty hack, avoiding an error when running BundleInstall
- name: comment colorscheme options
  lineinfile: >
    dest='~/.vimrc'
    regexp='^colorscheme Tomorrow-Night-Eighties'
    line='"colorscheme Tomorrow-Night-Eighties'
    state=present

- name: install all bundle
  command: vim +BundleInstall +qall

# now we can safely activate colorscheme options
- name: comment colorscheme options
  lineinfile: >
    dest='~/.vimrc'
    regexp='^"colorscheme Tomorrow-Night-Eighties'
    line='colorscheme Tomorrow-Night-Eighties'
    state=present
